server:
  host:
  port:
  apikey:

database:
  username:
  password:
  host:
  port:
  dbname:
  minconns: 15
  maxconns: 60
  maxconnlifetime: 45 # In minute
  maxconnidletime: 60 # In minute

log:
  level: 6
  formatter: text # "text" or "json"
  output: console # "console" or "file"
  filepath: ./app.log # Works when output = "file"

test:
  timeout: 30 # In second
